modLoader="javafml"
loaderVersion="[34,)"
license="MIT"

[[mods]]
modId="playground"
version="${file.jarVersion}"
displayName="Stoney's Playground"
# The description text for the mod (multi line!) (#mandatory)
description='''
Base mod for all my mod development.
'''

[[dependencies.playground]]
    modId="forge"
    mandatory=true
    versionRange="[34.0.0,)"
    ordering="NONE"
    side="BOTH"