modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="playground"
version="${version}"
displayName="Stoney's Playground"
# The description text for the mod (multi line!) (#mandatory)
description='''
My personal space for testing and experimentation.
'''

[[dependencies.playground]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="NONE"
    side="BOTH"